theme = "gruvbox"

[editor]
mouse = true
# auto-format = true
# auto-save = true
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "always"
scrolloff = 8
soft-wrap = { enable = true }
lsp.display-inlay-hints = true
lsp.display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "register" ]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
center = ["version-control", "file-name"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_visual_line_up", "paste_before" ]
A-j = ["extend_to_line_bounds", "delete_selection", "move_visual_line_down", "paste_before" ]
A-h = ["delete_selection", "move_char_left", "paste_before"]
A-l = ["delete_selection", "paste_after"]


[keys.insert]
C-s = "signature_help"
